# Generated by Django 4.2.5 on 2023-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
